### ISSUE TITLE
New option - do not mark moved thread/posts as unread

### ISSUE THREAD

**Issue by Cu8eeeR** [lukasamd/MyBB-View_Unread_posts#11]
New option - do not mark moved thread/posts as unread

When you move (moderator) any post or the whole thread -> it is marked as unread. Quite uncomfortable for users when I move a lot of threads during the day.

Is possible to disable the counting for moved posts or even better threads, or separately? Or choose which forum wont be counted into unreads when I move threads here?

@lukasamd

**Comment by lukasamd** [comment]
I think is impossible. Mark/unread signs are "calulated" only by post / thread / forum datelines. if you changed post forum (when post is moved from one forum to another), it must be visible as unread - I can, but I should not mark that new forum as read (because we don't know the contex).
