### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by thunderclap82** [lukasamd/MyBB-View_Unread_posts#12]
I deactivated the plugin the install the 1.6 update, and when I went to activate it I keep getting the following error:

MyBB has experienced an internal SQL error and cannot continue.

```
SQL Error:
1366 - Incorrect integer value: 'NULL' for column 'gid' at row 1
Query:
INSERT INTO mybb_settinggroups (`gid`,`name`,`title`,`description`,`disporder`,`isdefault`) VALUES ('NULL','unreadPosts','View Unread Posts','Settings for plugin \"View Unread Posts\"',105,'0')
```

Any ideas how to resolve this?

I'm running MyBB 1.8.10 on Ubuntu 16.04 and PHP7.

**Comment by lukasamd** [comment]
MyBB 1.6.x is not supported by this plugin.

**Comment by lukasamd** [comment]
Sorry, do you mean plugin 1.6 version, or MyBB 1.6?

**Comment by lukasamd** [comment]
And what database do you use (type and version)?

**Comment by thunderclap82** [comment]
I amended my first post. Plugin version 1.6 on MyBB 1.8.10. The server is running Ubuntu 16.04 with PHP7.

**Comment by thunderclap82** [comment]
I'm running MySQLi 5.7.17.

**Comment by SvePu** [comment]
@lukasamd - I've added a fix

**Comment by thunderclap82** [comment]
Thank you for such a quick investigation into this. Unfortunately, I just tried installing the new version you posted here and the error is still showing.

![screen shot 2017-02-20 at 10 45 53 am](https://cloud.githubusercontent.com/assets/18503620/23134373/33da8bae-f75a-11e6-9acd-b805e7081f63.png)

**Comment by SvePu** [comment]
@thunderclap82 - this is from another file ... I'll take a look

**Comment by SvePu** [comment]
@thunderclap82 - Added template install fix to PR #13

**Comment by thunderclap82** [comment]
That did it. Thank you so much for your quick turnaround.

**Comment by SvePu** [comment]
You're welcome!

**Comment by lukasamd** [comment]
@SvePu Thanks for very fast help for other user. I will fix it, but I don't want change my code structure and convention, so I must reject that merge request.

**Comment by SvePu** [comment]
@lukasamd - no problem.....it's your party ;)
