### ISSUE TITLE
Read items do not appear to be marked read unless 'mark forum read' is clicked

### ISSUE THREAD

**Issue by pjsgsy** [lukasamd/MyBB-View_Unread_posts#17]
Hi,

I installed the plugin and got it working. I noticed that if it lists 2 messages for example, I click on those 2 messages and read them, then click the view unread messages link again, the 2 messages are still there. They are not market as read, even though I read them. Unless I click the 'mark forum' read board at the time, they stay there. This does not appear to happen in the in-built read/not read marker. Is this expected? Is there a way around this?   Thanks.

**Comment by lukasamd** [comment]
It should automatically mark thread as read. I will test this with newest
MyBB version.
-- 
Pozdrawiam,
Łukasz Tkacz
