### ISSUE TITLE
PHP 7.2.2

### ISSUE THREAD

**Issue by qvidard** [lukasamd/MyBB-View_Unread_posts#18]
Hello,

In admin panel I have a lot of communicates  `Use of undefined constant THIS_SCRIPT - assumed 'THIS_SCRIPT' (this will throw an Error in a future version of PHP) `

I am using PHP 7.2.2

The same situation is in Fast Quote plugin.

![php error](https://user-images.githubusercontent.com/32547771/37635817-384b90d2-2bfe-11e8-8003-10fbd5a9a1d4.png)

**Comment by lukasamd** [comment]
Fixed in 1.11
