### ISSUE TITLE
Plugin is not visible at all

### ISSUE THREAD

**Issue by FurkanGozukara** [lukasamd/MyBB-View_Unread_posts#19]
I have uninstalled previous and installed latest View Unread Posts (1.11)

but still nothing visible on my screen

I am using Dark-Fire theme

Probably a template is missing?

help is appreciated

Here my forum : http://forum.pokemonpets.com

![image](https://user-images.githubusercontent.com/19240467/50178053-8f4e1880-0314-11e9-8c6e-0e667d047f25.png)

**Comment by lukasamd** [comment]
Add 

`<!-- UNREADPOSTS_LINK --> `

to template where you want display link (best option is to use header_welcomeblock_member_search)

Also, check headerinclude & footer templates, they should contain:

`<!-- UNREADPOSTS_CSS -->`

and

`<!-- UNREADPOSTS_JS -->`
