### ISSUE TITLE
1.13 - broken counter... again :(

### ISSUE THREAD

**Issue by Eldenroot** [lukasamd/MyBB-View_Unread_posts#24]
OK, v1.13 is much better than v1.12.

There are no more own posts marked as unread etc.

But, there is still one issue and I found the way how to reproduce it:
When you click on the icon "go to the first unread" or click on the thread subject -> unread posts are marked as read and the post counter is fine (in /search.php?action=unreads page). 

However when you click on the "thread subject" in displayforum_thread -> posts are not marked as read (you can see the unread "text" in the top right corner of the post).

@lukasamd  - I know, you wrote that v1.13 is the last one, so I created this issue for other users, I would like to see more updates but I understand completely that MyBB is only a hobby for you and it is quite time consuming :(

**Comment by lukasamd** [comment]
@Eldenroot I think it may be correct - this mod mark posts as read ONLY if you shown them. Example: thread has 10 pages with unread posts on 9 and 10. If you click thread subject on forumdisplay, you will open first thread page -> plugin will NOT mark this thread as read (because you haven't seen new posts yet)

**Comment by lukasamd** [comment]
To clarify: if you open page 9... thread will be still unread - but only for page 10.

**Comment by Eldenroot** [comment]
@lukasamd - ok, but this was not there in v1.11. Am I right?

**Comment by lukasamd** [comment]
It should work in that way always - I think it may be broken because of invalid timestamps fixed on latest version and related to displaying "unread post" on our posts. 

I think it's the best option, because it can really show us >>UNREAD<< posts. We must just see them, to allow plugin marks thread as read.

**Comment by Eldenroot** [comment]
Thats possible because it is really something new for me and my users :)

OK, and is possible to somehow (maybe setting) set to mark all posts read when I visit the thread? 

To clarify my idea - just imagine this situation - you are in the thread with a lot of new posts but according to the discussion you see that the thread is not your cup of coffee and you do not wanna continue in reading another posts in that thread... unfortunately you have to go through them to the last post to make all posts in that thread read. 

I think adding a setting for this would be a really useful for admins.

Just my 2 cents :)

**Comment by lukasamd** [comment]
You can always mark thread as read from search results (there is an option to make this in ajax by clicking thread icon).

**Comment by Eldenroot** [comment]
Yes, maybe would be better somehow mark all post read inside the thread. Is there any way how to integrate on my own? Any url link? :)

**Comment by Eldenroot** [comment]
@lukasamd - I think there is a conflict with your second plugin which I use together with "Unread posts" - https://community.mybb.com/mods.php?action=view&pid=200

When I edit my post -> it is marked as unread for others (because of Mark edited as unread plugin) -> so the unread counter display "1 unread post" (it counts my edited post). Others can see the thread in the search list, they can redirect to the last edited post but it is not marked as read (you have to manually mark all threads as read in search page).
