### ISSUE TITLE
correct version 1.14 in zip ? # error log at server / hoster

### ISSUE THREAD

**Issue by schauan** [lukasamd/MyBB-View_Unread_posts#27]
Version:
after installing as update from 1.11 to 1.14 I saw in my acp a note abaout a newer version and to update my VUP from 1.13 to 1.14 I looked for "13" in the unreadpost.php, and at line 52 I found it :        'version' => '1.13',

Error log:
Every minute (my vup refresh time) I get this line in my log:
 
clever-excel-forum.net anon-87-151-175-98.t-ipconnect.de - - [18/Dec/2020:00:43:20 +0100] "GET /xmlhttp.php?action=unreadPosts_getUnreads&fid0 HTTP/1.1" 200 193 "https://www.clever-excel-forum.net/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60"

PHP Version 7.3
MySQL Version 5.6.42
Mybb Version 1.8.24

**Comment by schauan** [comment]
the point with Error log was incorrect - I had read the access log :-(

**Comment by schauan** [comment]
also in changlog.txt is no description about changes to 1.14 Last point is:

Version 1.13
    * Add fixes for mod tools
    * Add fixes for mark as read
    * It's last version - mod will not updated anymore

**Comment by lukasamd** [comment]
@schauan 1.14 is correct latest version. I forgot to update this version on config file, but it's only the one issue and you can change this version manually. 

I will probably not provide any updates more.

**Comment by schauan** [comment]
ok, thank you for this information. I had done it some days before, but I wasn't sure, if it is correctly.
