### ISSUE TITLE
inc/functions_indicators.php

### ISSUE THREAD

**Issue by amaryllion** [lukasamd/MyBB-View_Unread_posts#3]
Bei den Dateien, die man hochladen soll, befindet sich die PHP-Datei "inc/functions_indicators.php", die zu den MYBB-Dateien gehört, überschrieben werden soll und dazu ganz eindeutig in einer älteren Version (MyBB 1.6) vorliegt. 
Ich finde es generell ziemlich unglücklich, dass bei einem Plugin überhaupt eine Quell-Datei von MyBB überschrieben werden muss.

**Comment by tom762** [comment]
Inside this file it's written: 

` * MyBB 1.6
` * Copyright 2010

This could be a mistake, however file is quite different compared to the original functions_indicators.php.

I wouldn't mind if the plugin worked. If I activate it, it looks ok, but when viewing forum, this error is shown:

` MyBB SQL Error
` MyBB has experienced an internal SQL error and cannot continue.
` Please contact the MyBB Group for technical support.

Can't make it to work. :/
