### ISSUE TITLE
Conflict with ProStats Plugin

### ISSUE THREAD

**Issue by cuthulino** [lukasamd/MyBB-View_Unread_posts#8]
Hey lukasamd
Our Community want to use this Plugin together with the ProStats Plugin.
But they dont work correct together.

When we activate View unread posts, the Threads do not get marked as read in the Prostats Plugin.
I can not say you what exactly goes wrong, i am no developer but maybe you can fix this?

Our community would also like to donate something for a fix.

**Comment by lukasamd** [comment]
Hello!
I checked ProStats - it uses default, and invalid method to get *true unread* posts. 
I can't do anything with that.

**Comment by cuthulino** [comment]
so Problem is made by ProStats?

**Comment by lukasamd** [comment]
Not exactly. MyBB has build-in bug with unread posts and all standard plugins "inherit" this issue. My plugin fix some problems, but ProStats author does not need to know about that.

So... it isn't ProStats bug.
It isn't View Unread bug also.
It's MyBB bug :)

**Comment by cuthulino** [comment]
bad to hear that.
